# Generated by Django 4.1.4 on 2023-02-18 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.CharField(choices=[('ECONOM', 'Экономный'), ('STANDARD', 'Стандартный'), ('VIP', 'VIP')], db_index=True, max_length=20, verbose_name='Тариф')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Полное имя')),
                ('telegram_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram Id')),
                ('telegram_username', models.CharField(blank=True, db_index=True, max_length=75, null=True, unique=True, verbose_name='Telegram Username')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Полное имя')),
                ('telegram_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram Id')),
                ('telegram_username', models.CharField(blank=True, db_index=True, max_length=75, null=True, unique=True, verbose_name='Telegram Username')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название заказа')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание заказа')),
                ('registered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_bot.client', verbose_name='заказчик')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_bot.contractor', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='История переписки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.order', verbose_name='заказ')),
            ],
        ),
    ]
