# Generated by Django 4.1.7 on 2023-02-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_client_telegram_id_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_bot.contractor', verbose_name='исполнитель'),
        ),
    ]
