# Generated by Django 4.1.7 on 2023-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_order_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('CLIENT', 'Заказчик'), ('CONTRACTOR', 'Исполнитель')], db_index=True, default='lol', max_length=20, verbose_name='Отправитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Не назначен'), ('IN_PROGRESS', 'В работе'), ('FINISHED', 'Выполнен')], db_index=True, default='NOT_ASSIGNED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
